language: ruby
rvm:
  - 2.2.4
before_install: gem install bundler -v 1.11.2
before_script: sudo apt-get install -y build-essential libsdl2-dev libsdl2-ttf-dev libpango1.0-dev libgl1-mesa-dev libfreeimage-dev libopenal-dev libsndfile-dev
